//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdress
    {
        public int AdressID { get; set; }
        public string AdressDescription { get; set; }
        public string AdressLocation { get; set; }
        public string AdressPhoneNumber { get; set; }
        public string AdressEmail { get; set; }
    }
}
